### ISSUE TITLE
Implement proper resugaring

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#10]
Currently resugaring and pretty-printing are combined into one pass. It would be better to have a resugaring pass that restores original surface syntax and then we could pretty-print that syntax.

# Ideas how to solve problems:

  * Remember function return type
  * Add `InferTy` to the type language to annotate holes
  * Desugar closures as open terms, ignore the environment

# TODO

  * [x] implement the above
  * [x] resugar from values to expressions

**Comment by jstolarek** [comment]
I have been working on this today and I need some help.

My primary assumption is that resugaring and desugaring are inverses. That is, I can resugar a desugared program and recover the original source. And then I can desugar such a resugared program and get back what I had before resugaring. Somehow I even consider that second property more important.

Firstly, the major problem of resugaring is the fact that the surface language is explicitly typed while the core language is not. So far I have identified two cases where this is problematic:

  1. **Function declarations**: In the surface language function's return type is explicit but is discarded during desugaring.  One possible solution is to reconstruct the return type using the function's body, but this would require implementing type reconstruction algorithm.
  
  2. **Holes**: in the surface language they are explicitly typed, but not in the core language. A tempting solution here is to add an InferTy that we would use during resugaring.  When encountered during desugaring InferTy would mean "assume this is the type we expect".  This would, however, lead to lots of extra complexity in the desugarer

A possible solution to both of the above problems would be to add extra type information for the sake of resugaring, ie. holes would retain explicit typing in core and funtions would carry the return type. I'm leaning towards that solution since it seems the simplest, but see below.

The second problem is this: when and what do we want to resugar? The current resugaring code resugars values since this is what we want to print to the user as a result of program evaluation. There is a helper function called val2exp in Core module, the rest of the logic being in Resugar module. So far I have been working on resugaring core **expressions** into surface expressions. If we want to resugar values then we need to figure out a way of converting values into core expressions, so we can then go back from core expressions into surface ones. This is mostly straightforward, but a few problems come up:

  * If we were to follow the approach of explicit typing of the core language then we would have to explicitly type the values as well. The problem again arises with holes.

  * Desugaring closures is also problematic because they store enviroments. If we want the desugared term to be closed then such an environment would have to be converted into a series of let bindings. The problem is to figure out the order of these let bindings. Doing some sort of dependency analysis seems like an overkill. An alternative approach would be to annotate every let binding during desugaring with a number that would indicate order. But again, we'll be cluttering our data representations for the purpose of resugaring. Or perhaps we'd be happy with returning an open term? Functions body in Core contains, after all, free variables. This seems reasonable but I'd like your opinion.

  * How to resugar trace values? Are we happy with resugaring just the value that was generated from the trace? If not then we have to pslice a trace and only then resugar

  * Resugaring values becomes even more paintful in the presence of references. How to resugar a label? Perhaps by taking value that it points to in the store and resugaring that value?

**Comment by jamescheney** [comment]
> the surface language is explicitly typed while the core language is not

The fact that the source language is explicitly typed is an artifact of the fact that we were lazy and didn't want to take the time to implement some kind of type inference.  So, we include type annotations solely to make typechecking easy.  I think the goal of resugaring is to produce a value/expression in terms of the source language rather than the core language.  So I would be 

Alternatively, I had in mind that resugaring would take both the *original* source term `t` and the desugared core term `u` (which might not be udentical to `desugar t`, it might be a prefix).  This would help with reconstituting the type annotations of functions, but not so much with holes.

Preserving the types of holes in the forward direction would not help much because when introducing holes in the (implicitly typed) core we would have to figure out what the type of the hole should be.  I think it would be better to make the hole-annotation optional in the source, and just ignore it when resugaring.

> when and what do we want to resugar?

There are two times:
* Resugaring values when printing a result value
* Resugaring expressions when printing / showing a sliced program.  (Currently I don't think we actually do this, instead sliced programs only get visualized, but we could add this.)

Notice that a result value that is a closure contains an expression/environment that in principle we could serialize via resugaring too.  Alternatively, when resugaring function values/closures we could just have a special value form that just says it's a function.  Likewise with traces and reference cell labels.  

Is this helpful?

**Comment by jstolarek** [comment]
>  I think the goal of resugaring is to produce a value/expression in terms of the source language rather than the core language.  So I would be

Yes, that is exactly my understanding. I'm afraid I don't see a conclusion - especially given the incomplete sentence :-)

> Alternatively, I had in mind that resugaring would take both the original source term t and the desugared core term u (which might not be udentical to desugar t, it might be a prefix).

That sounds a bit like an overkill. Wouldn't it be easier to extract the needed type annotations from the original AST and store them in the desugared tree?

>  I think it would be better to make the hole-annotation optional in the source, and just ignore it when resugaring.

Please correct mi if I'm wrong, but this is essentially isomorphic to my idea of introducing `InferTy` to the type language. Because when the type annotation is missing from a hole (in the syntax language) then we have to handle such case during desugaring anyway. Which is the same as inferring the type of a hole. Unless we assume that the holes in the source code must always have annotations. But this breaks my assumption that resugared code could be desugared again.

> Resugaring expressions when printing / showing a sliced program. (Currently I don't think we actually do this, instead sliced programs only get visualized, but we could add this.)

No, we don't. Which reminds me of another problem - I'll start a separate ticket.

> Notice that a result value that is a closure contains an expression/environment that in principle we could serialize via resugaring too.

We can serialize it only if we figure out how to order the bindings in the environment. But the more I think about it the more I am convinced that we don't need to worry about this and just serialize the closure as an open term. I don't think we will ever want to have an explicit closure written down in the source code.

>  Alternatively, when resugaring function values/closures we could just have a special value form that just says it's a function.

I fail to see how this would work.

**Comment by jamescheney** [comment]
Argh, the incomplete sentence should be something like "So I would be happy to make the type annotations in the source optional, and leave them undefined when resugaring, because we don't necessarily care about re-typechecking a slice of an initially well-typed program."

> That sounds a bit like an overkill. Wouldn't it be easier to extract the needed type annotations from the original AST and store them in the desugared tree?

It depends what the goal is.  If we are not using the type annotations in the desugared tree otherwise, why not reuse the information that was already present in the source?  Perhaps it would be more work than needed though, in which case leaving the type annotations optional would be fine.

> Please correct mi if I'm wrong, but this is essentially isomorphic to my idea of introducing InferTy to the type language.

Yes, I should have pointed that out.  (But by "ignore it" I mean not even bothering to retypecheck after resugaring, so that would not require inferring types.)

> I fail to see how this would work.

Sorry, I was probably being too hand-wavy.  I meant that - purely for the purpose of resugaring core values to something printable - we could introduce special cases of values for "opaque" functions, references, etc. that just print out to `<fun>` or `<ref>` as in the ML REPL.

**Comment by jstolarek** [comment]
> we don't necessarily care about re-typechecking a slice of an initially well-typed program.

I haven't considered this approach. Meaning: I wanted the resugared programs to be valid.

> If we are not using the type annotations in the desugared tree otherwise, why not reuse the information that was already present in the source?

Another thing that just crossed my mind is that this approach might be difficult to implement (or not possible at all?) when resugaring values. Say we have value `[1,2,_,4]` and the original source was `map (+1) [0,1,_:int,3]`. How do we use original AST to resugar the value?

I think I now see to alternative ways of proceeding:

  1. Assume that resugared programs are supposed to be valid programs that can be recompiled. This requires solving all the problems that I have pointed out.

  2. Assume that the only purpose of resugared program is to be pretty-printed and hand-wave all the problems that I pointed out.

Given the time constraints I am now leaning towards (2) although I feel this is stopping half-way. Something tells me that, if we keep developing that code in the future, we will at some point have to implement (1).

That being said, I think if we go with (2) we should have a separate syntax tree to represent a resugared program. This will be much simpler than extending expression syntax tree with constructs that can only arise during resugaring and having to deal with them in the desugaring process. Does that sound reasonable?

**Comment by jamescheney** [comment]
> Say we have value [1,2,_,4] and the original source was map (+1) [0,1,_:int,3]. How do we use original AST to resugar the value?

This is not one of the cases of resugaring I had in mind.  I had in mind two situations:

* given a core value (resulting from evaluating a core program), translate it back to a readable source value.  In this case we do not have a "source expression" to use, and I am less concerned about being able to typecheck the (holes or expressions in the) resugared form.  For example, translate inl(1,inl(2,inl(_,inl(4,inr())))) to [1,2,_,4].
* given a sliced core expression (resulting from slicing a core program obtained by translation from a source program), translate it back to a readable slice of the source value.  In this case restoring the type information to obtain a well-typed source value would be nice, but I can live without it.  

It may be that I have been conflating these two different situations.  

> Does that sound reasonable?

In the interest of making progress, (2) this sounds fine - at least it wouldn't complicate existing data structures further.  In the work on slicing we did not consider actually rerunning (or re-typechecking) sliced programs containing holes, just printing/visualizing them; the forward semantics in the paper is defined as a way of validating the backward slicing semantics, but not provided as an implemented thing.  We could consider this or even more general forms of replay (for example, on different inputs) but this would be a different problem.
