### ISSUE TITLE
Do we need `pp_partial`?

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#17]
I recall asking about the motivation for having `pp_partial` but I can't recall what it was. Do we really need `pp_partial` or could we simplify `PP` type class to only contain `pp`? Is it possible that `pp_partial` is a leftover from time when `visualize` was not yet implemented?

**Comment by jamescheney** [comment]
Yes, I think this may be a holdover from early stages when we used it to visualize differential slices textually rather than using visualize.  We could of course still provide this capability by exposing pp_partial as a function for printing differential expression or trace slices.  Or we could remove it and just do "normal" pretty printing.  (Or we could encode differential slices in a different way.)  In any case, happy with removing / simplifying for now since it seems we are not using pp_partial as originally intended.

**Comment by jstolarek** [comment]
Fixed. I removed the `PP` class altogether. We know use `Pretty` type class from the `pretty` library. Use `pPrint` function instead of `pp`.
